# Generated by Django 5.2.17 on 2026-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False, help_text="Use for port 465. Don't enable both TLS and SSL.")),
                ('username', models.CharField(help_text='SMTP login email', max_length=255)),
                ('password', models.CharField(help_text='For Gmail, use an App Password', max_length=255)),
                ('from_email', models.CharField(help_text='e.g. NTTS Mobility <info@nttsmobility.com>', max_length=255)),
                ('receiver_email', models.EmailField(help_text='Where enquiry notifications are sent', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
    ]
