# Generated by Django 5.2.17 on 2026-09-30 08:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookingmodal_herosection_sitesettings_vehicleclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('eyebrow', models.CharField(help_text='e.g. NTTS LIVE MOBILITY DECK', max_length=60, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=100, verbose_name='Heading')),
                ('footer_text', models.CharField(blank=True, help_text='Leave empty to hide it', max_length=120, verbose_name='Small text next to arrows')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Change slides automatically')),
                ('autoplay_seconds', models.PositiveIntegerField(default=6, verbose_name='Seconds per slide')),
            ],
            options={
                'verbose_name': '4. Fleet Slider – Heading',
                'verbose_name_plural': '4. Fleet Slider – Heading',
            },
        ),
        migrations.CreateModel(
            name='FleetSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('tab_label', models.CharField(help_text='Short name on the top-right tab, e.g. Exec SUV', max_length=30, verbose_name='Tab name')),
                ('tab_icon', models.CharField(choices=[('sedan', 'Sedan car'), ('city', 'City car'), ('suv', 'SUV'), ('ev', 'Electric car'), ('van', 'Van')], default='sedan', max_length=10, verbose_name='Tab icon')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. FIRST-CLASS CHAUFFEUR', max_length=40, verbose_name='Small tag')),
                ('title', models.CharField(max_length=80, verbose_name='Car name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Car on a transparent background (PNG) works best', max_length=255, null=True, verbose_name='Car photo')),
                ('image_alt', models.CharField(blank=True, help_text='For Google', max_length=150, verbose_name='Photo description')),
            ],
            options={
                'verbose_name': 'Fleet slide',
                'verbose_name_plural': '4. Fleet Slider – Slides',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bookingmodal',
            options={'verbose_name': '3. Booking Popup', 'verbose_name_plural': '3. Booking Popup'},
        ),
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ride booking', 'verbose_name_plural': 'Ride Bookings (from website)'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': '2. Hero Banner', 'verbose_name_plural': '2. Hero Banner'},
        ),
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Menu link', 'verbose_name_plural': 'Menu links'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': '1. Website Settings & Menu', 'verbose_name_plural': '1. Website Settings & Menu'},
        ),
        migrations.AlterModelOptions(
            name='smtpsettings',
            options={'verbose_name': 'Email Settings (SMTP)', 'verbose_name_plural': 'Email Settings (SMTP)'},
        ),
        migrations.AlterModelOptions(
            name='vehicleclass',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Car option', 'verbose_name_plural': '3. Booking Popup – Car Options'},
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='badge_text',
            field=models.CharField(max_length=60, verbose_name='Small tag'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='button_prefix',
            field=models.CharField(help_text='The chosen car is added after it: "Request" shows as "Request NTTS Luxe"', max_length=30, verbose_name='Button – first word'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='contact_heading',
            field=models.CharField(default='Your Details', max_length=60, verbose_name='Customer details – heading'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='departing_highlight',
            field=models.CharField(help_text='e.g. Within 3–5 Mins', max_length=40, verbose_name='Departure – bold text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='departing_label',
            field=models.CharField(help_text='e.g. Departing:', max_length=30, verbose_name='Departure – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='departing_note',
            field=models.CharField(help_text='e.g. (Fastest match)', max_length=60, verbose_name='Departure – note'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='destination_label',
            field=models.CharField(max_length=40, verbose_name='Drop – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='destination_placeholder',
            field=models.CharField(max_length=120, verbose_name='Drop – example text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='email_label',
            field=models.CharField(default='Email (optional)', max_length=30, verbose_name='Email – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='email_placeholder',
            field=models.CharField(default='Enter your email', max_length=60, verbose_name='Email – example text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='footer_note',
            field=models.CharField(max_length=200, verbose_name='Note under button'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='name_label',
            field=models.CharField(default='Full Name', max_length=30, verbose_name='Name – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='name_placeholder',
            field=models.CharField(default='Enter your name', max_length=60, verbose_name='Name – example text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='nearby_suffix',
            field=models.CharField(help_text='The number is added for you: "options nearby" shows as "4 options nearby"', max_length=40, verbose_name='Text after car count'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='phone_label',
            field=models.CharField(default='Mobile Number', max_length=30, verbose_name='Mobile – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='phone_placeholder',
            field=models.CharField(default='Enter your mobile number', max_length=60, verbose_name='Mobile – example text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='pickup_label',
            field=models.CharField(max_length=40, verbose_name='Pickup – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='pickup_placeholder',
            field=models.CharField(max_length=120, verbose_name='Pickup – example text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='ride_now_label',
            field=models.CharField(max_length=30, verbose_name='“Ride now” button'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='schedule_date_label',
            field=models.CharField(default='Pickup Date', max_length=30, verbose_name='Schedule – date title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='schedule_label',
            field=models.CharField(max_length=30, verbose_name='“Schedule” button'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='schedule_time_label',
            field=models.CharField(default='Pickup Time', max_length=30, verbose_name='Schedule – time title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Line under heading'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='success_button_text',
            field=models.CharField(max_length=30, verbose_name='Close button text'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='success_footer_note',
            field=models.CharField(blank=True, help_text='Leave empty to hide it', max_length=100, verbose_name='Small note at bottom'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='success_message',
            field=models.CharField(max_length=200, verbose_name='Thank-you message'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='success_title',
            field=models.CharField(max_length=60, verbose_name='Thank-you heading'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='vehicle_heading',
            field=models.CharField(max_length=60, verbose_name='Car list heading'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Only visible to you', verbose_name='Your notes'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received on'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_option',
            field=models.CharField(blank=True, max_length=60, verbose_name='Date chosen'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Drop'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email alert sent'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='pickup',
            field=models.CharField(max_length=255, verbose_name='Pickup'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='quoted_price',
            field=models.CharField(blank=True, max_length=20, verbose_name='Price shown'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='ride_type',
            field=models.CharField(choices=[('now', 'Ride Now'), ('schedule', 'Scheduled')], default='now', max_length=10, verbose_name='Ride type'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='ride_window',
            field=models.CharField(blank=True, max_length=60, verbose_name='Time chosen'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pickup date'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup time'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicleclass', verbose_name='Car option'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_alt',
            field=models.CharField(blank=True, help_text='What the photo shows, for Google', max_length=150, verbose_name='Photo description'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Wide landscape photo, at least 1920 px wide', max_length=255, null=True, verbose_name='Background photo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text',
            field=models.CharField(help_text='e.g. NEXT-GEN URBAN TRANSIT', max_length=60, verbose_name='Small tag above heading'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(max_length=40, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='card_title',
            field=models.CharField(max_length=60, verbose_name='Box heading'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='date_label',
            field=models.CharField(max_length=30, verbose_name='Date – title'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='date_options',
            field=models.TextField(help_text='Write one choice per line. The first one is picked by default.', verbose_name='Date – choices'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(verbose_name='Short paragraph'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='destination_label',
            field=models.CharField(max_length=40, verbose_name='Drop – title'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='destination_placeholder',
            field=models.CharField(help_text='Grey hint shown inside the empty box', max_length=120, verbose_name='Drop – example text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='distance_text',
            field=models.CharField(help_text='e.g. 0.8 km away', max_length=30, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_initials',
            field=models.CharField(help_text='Shown when there is no photo', max_length=4, verbose_name='Driver initials'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_name',
            field=models.CharField(max_length=50, verbose_name='Driver name'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_phone',
            field=models.CharField(blank=True, help_text='Optional. Makes the call icon work.', max_length=20, verbose_name='Driver phone'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional', max_length=255, null=True, verbose_name='Driver photo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_rating',
            field=models.CharField(help_text='e.g. 4.98', max_length=10, verbose_name='Driver rating'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='driver_trips',
            field=models.CharField(help_text='e.g. (1,420 trips)', max_length=30, verbose_name='Trips count'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='eta_text',
            field=models.CharField(help_text='e.g. Avg ETA 2.4 min', max_length=40, verbose_name='Arrival time tag'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='fleet_label',
            field=models.CharField(help_text='e.g. NTTS Fleet', max_length=50, verbose_name='Right side title'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='pickup_label',
            field=models.CharField(max_length=40, verbose_name='Pickup – title'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='pickup_placeholder',
            field=models.CharField(help_text='Grey hint shown inside the empty box', max_length=120, verbose_name='Pickup – example text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='ride_window_label',
            field=models.CharField(max_length=30, verbose_name='Time – title'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='ride_window_options',
            field=models.TextField(help_text='Write one choice per line. The first one is picked by default.', verbose_name='Time – choices'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Heading – first line'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_highlight',
            field=models.CharField(max_length=120, verbose_name='Heading – green line'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='tracking_label',
            field=models.CharField(help_text='e.g. Tracking Chauffeur', max_length=50, verbose_name='Top tag'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='vehicle_details',
            field=models.CharField(max_length=80, verbose_name='Car model / colour'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='vehicle_name',
            field=models.CharField(max_length=50, verbose_name='Car name'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Menu text'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='link',
            field=models.CharField(help_text='A section like #fleet, or a full web address', max_length=255, verbose_name='Goes to'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.nttsmobility.com/', verbose_name='Website address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Small square image, e.g. 64 × 64', max_length=255, null=True, verbose_name='Browser tab icon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_alt',
            field=models.CharField(default='NTTS Mobility', help_text='Read by Google and screen readers', max_length=150, verbose_name='Logo description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(help_text='The short text under the title in Google. Aim for 140–160 letters.', max_length=170, verbose_name='Page description (Google)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate with commas', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(help_text='Shown in Google results and the browser tab. Keep under 60 letters.', max_length=70, verbose_name='Page title (Google)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_cta_link',
            field=models.CharField(blank=True, default='#book', max_length=255, verbose_name='Button link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_cta_opens_booking',
            field=models.BooleanField(default=True, help_text='Untick to send visitors to the link below instead', verbose_name='Open booking popup on click'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_cta_text',
            field=models.CharField(default='Book a Ride', max_length=50, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_description',
            field=models.CharField(blank=True, help_text='Leave blank to use the page description.', max_length=200, verbose_name='Share description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Picture shown when the link is shared. Best size 1200 × 630.', max_length=255, null=True, verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title when the link is shared on WhatsApp / Facebook. Leave blank to use the page title.', max_length=100, verbose_name='Share title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots',
            field=models.CharField(default='index, follow', help_text='Keep "index, follow" so Google can list the site', max_length=50, verbose_name='Search engine visibility'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='NTTS Mobility', max_length=100, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_email',
            field=models.CharField(help_text='e.g. NTTS Mobility <info@nttsmobility.com>', max_length=255, verbose_name='Sender name & email'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='host',
            field=models.CharField(default='smtp.gmail.com', help_text='For Gmail keep smtp.gmail.com', max_length=255, verbose_name='Mail server'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Emails on'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=models.CharField(help_text='For Gmail, create an App Password', max_length=255, verbose_name='App password'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='port',
            field=models.PositiveIntegerField(default=587, help_text='Gmail: 587 (with TLS) or 465 (with SSL)'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='receiver_email',
            field=models.EmailField(help_text='New ride requests are emailed here', max_length=254, verbose_name='Send booking alerts to'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, help_text="Only for port 465. Don't tick both TLS and SSL.", verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(help_text='The email account that sends the mails', max_length=255, verbose_name='Login email'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g. POPULAR. Leave empty for no tag.', max_length=20, verbose_name='Highlight tag'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Numbers only, e.g. 80', max_digits=8, verbose_name='Starting price'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='button_name',
            field=models.CharField(help_text='Shown as "Request <this>" when the car is picked', max_length=40, verbose_name='Name on button'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='details',
            field=models.CharField(help_text='e.g. 4 seats · 3m away', max_length=80, verbose_name='Short details'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Car on a plain / transparent background', max_length=255, null=True, verbose_name='Car photo'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one car can be picked by default', verbose_name='Picked by default'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='name',
            field=models.CharField(help_text='e.g. Compact Sedan', max_length=60, verbose_name='Car type'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='price_suffix',
            field=models.CharField(default='base', max_length=20, verbose_name='Text after price'),
        ),
        migrations.CreateModel(
            name='FleetSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Luggage', max_length=30, verbose_name='Title')),
                ('value', models.CharField(help_text='e.g. 5 Suitcases', max_length=40, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.fleetslide')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features (shown in a row under the description)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
