# Generated by Django 5.2.17 on 2026-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fleetsection_fleetslide_alter_bookingmodal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('number', models.CharField(help_text='Type it as you want it shown, e.g. 10M+, 4.9, 50+, 24/7', max_length=20, verbose_name='Number')),
                ('show_star', models.BooleanField(default=False, help_text='Tick for ratings, e.g. 4.9 ★', verbose_name='Show star after number')),
                ('label', models.CharField(max_length=60, verbose_name='Text below number')),
                ('color', models.CharField(choices=[('green', 'Green'), ('dark', 'Dark')], default='green', max_length=10, verbose_name='Number colour')),
            ],
            options={
                'verbose_name': 'Stat box',
                'verbose_name_plural': '5. Stats (numbers row)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
