# Generated by Django 5.2.17 on 2026-09-30 08:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_statitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('badge_text', models.CharField(help_text='e.g. FLEET & RIDES', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Short paragraph')),
                ('side_badge_text', models.CharField(blank=True, help_text='e.g. 100% Carbon-Neutral Fleet Options. Leave empty to hide.', max_length=60, verbose_name='Tag on the right')),
            ],
            options={
                'verbose_name': '6. Fleet & Rides – Heading',
                'verbose_name_plural': '6. Fleet & Rides – Heading',
            },
        ),
        migrations.CreateModel(
            name='RideOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('name', models.CharField(help_text='e.g. Compact Sedan', max_length=60, verbose_name='Car type')),
                ('currency_symbol', models.CharField(default='₹', max_length=5, verbose_name='Currency')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Numbers only, e.g. 80', max_digits=8, verbose_name='Starting price')),
                ('price_suffix', models.CharField(default='base', max_length=20, verbose_name='Text after price')),
                ('description', models.TextField(verbose_name='Short description')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Car photo')),
                ('image_alt', models.CharField(blank=True, help_text='For Google', max_length=150, verbose_name='Photo description')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. TOP TIER. Leave empty for no tag.', max_length=30, verbose_name='Tag on photo')),
                ('features', models.TextField(help_text='Write one feature per line, e.g. 4 Seats', verbose_name='Features')),
                ('button_text', models.CharField(help_text='e.g. Book Sedan', max_length=30, verbose_name='Button text')),
                ('is_featured', models.BooleanField(default=False, help_text='Green border and filled green button', verbose_name='Highlight this card')),
                ('booking_car', models.ForeignKey(blank=True, help_text='When the button is clicked, the booking popup opens with this car already picked. Optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicleclass', verbose_name='Car picked in booking popup')),
            ],
            options={
                'verbose_name': 'Ride card',
                'verbose_name_plural': '6. Fleet & Rides – Cars',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
