# Generated by Django 5.2.17 on 2026-09-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ridessection_rideoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleclass',
            name='image',
        ),
        migrations.AlterField(
            model_name='rideoption',
            name='booking_car',
            field=models.ForeignKey(blank=True, help_text='Clicking the button opens the booking popup with this car picked. The photo you upload here is also shown for that car in the popup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_cards', to='core.vehicleclass', verbose_name='Linked car in booking popup'),
        ),
    ]
