# Generated by Django 5.2.17 on 2026-09-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vehicleclass_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('icon', models.CharField(choices=[('location', 'Location pin'), ('sliders', 'Settings sliders'), ('shield', 'Safety shield'), ('car', 'Car'), ('phone', 'Phone'), ('clock', 'Clock'), ('star', 'Star'), ('card', 'Payment card')], default='location', max_length=10, verbose_name='Icon')),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue')], default='green', help_text='Colour of the step tag, icon and dot', max_length=10, verbose_name='Colour')),
                ('title', models.CharField(max_length=80, verbose_name='Step heading')),
                ('description', models.TextField(verbose_name='Description')),
                ('highlight_text', models.CharField(blank=True, help_text='e.g. Instant GPS coordinate detection. Leave empty to hide.', max_length=80, verbose_name='Highlight line at bottom')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': '7. How It Works – Steps',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('badge_text', models.CharField(help_text='e.g. THE PROCESS', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Short paragraph')),
                ('step_word', models.CharField(default='STEP', help_text='Numbers are added for you in order: STEP 01, STEP 02…', max_length=15, verbose_name='Word before step number')),
            ],
            options={
                'verbose_name': '7. How It Works – Heading',
                'verbose_name_plural': '7. How It Works – Heading',
            },
        ),
    ]
