# Generated by Django 5.2.17 on 2026-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_step_stepssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('icon', models.CharField(choices=[('id_card', 'ID card'), ('satellite', 'Satellite / GPS'), ('sos', 'SOS / emergency'), ('phone_lock', 'Phone with lock'), ('handshake', 'Two-way / handshake'), ('shield', 'Shield'), ('heart', 'Heart / care'), ('camera', 'Camera')], default='shield', max_length=12, verbose_name='Icon')),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], default='green', max_length=10, verbose_name='Icon colour')),
                ('title', models.CharField(max_length=60, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Safety feature',
                'verbose_name_plural': '8. Safety – Feature Cards',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('badge_text', models.CharField(help_text='e.g. ISO 27001 CERTIFIED SAFETY', max_length=60, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Short paragraph')),
                ('show_highlight', models.BooleanField(default=True, verbose_name='Show highlight box')),
                ('highlight_title', models.CharField(blank=True, help_text='e.g. NTTS Shield™ Active', max_length=60, verbose_name='Highlight box – heading')),
                ('highlight_text', models.CharField(blank=True, max_length=200, verbose_name='Highlight box – text')),
            ],
            options={
                'verbose_name': '8. Safety – Heading',
                'verbose_name_plural': '8. Safety – Heading',
            },
        ),
        migrations.AddField(
            model_name='stepssection',
            name='banner_badge',
            field=models.CharField(blank=True, help_text='e.g. 99.98% DISPATCH UPTIME. Leave empty to hide.', max_length=40, verbose_name='Banner tag (right side)'),
        ),
        migrations.AddField(
            model_name='stepssection',
            name='banner_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner text'),
        ),
        migrations.AddField(
            model_name='stepssection',
            name='banner_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Banner heading'),
        ),
        migrations.AddField(
            model_name='stepssection',
            name='show_banner',
            field=models.BooleanField(default=True, verbose_name='Show green banner under the steps'),
        ),
    ]
