# Generated by Django 5.2.17 on 2026-09-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_safetyfeature_safetysection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('badge_text', models.CharField(help_text='e.g. TRANSPARENT TARIFF', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Short paragraph')),
            ],
            options={
                'verbose_name': '9. Pricing – Heading',
                'verbose_name_plural': '9. Pricing – Heading',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(help_text='e.g. COMPACT SEDAN', max_length=40, verbose_name='Plan name')),
                ('icon', models.CharField(choices=[('sedan', 'Sedan car'), ('executive', 'Executive car'), ('ev', 'Electric car'), ('suv', 'SUV / big car')], default='sedan', max_length=10, verbose_name='Icon')),
                ('price_suffix', models.CharField(default='/ base fare', max_length=30, verbose_name='Text after price')),
                ('features', models.TextField(help_text='Write one feature per line', verbose_name='Features (with tick marks)')),
                ('button_text', models.CharField(help_text='e.g. Select Sedan', max_length=30, verbose_name='Button text')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. MOST POPULAR. Leave empty for no tag.', max_length=30, verbose_name='Tag on top')),
                ('is_featured', models.BooleanField(default=False, help_text='Green border and filled green button', verbose_name='Highlight this plan')),
                ('car', models.ForeignKey(help_text='The price is taken from this car in “3. Booking Popup – Car Options”, and the button opens the booking popup with this car picked.', on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plans', to='core.vehicleclass', verbose_name='Linked car')),
            ],
            options={
                'verbose_name': 'Pricing plan',
                'verbose_name_plural': '9. Pricing – Plans',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
