# Generated by Django 5.2.17 on 2026-09-30 08:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pricingsection_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★  5 stars'), (4, '★★★★  4 stars'), (3, '★★★  3 stars'), (2, '★★  2 stars'), (1, '★  1 star')], default=5, verbose_name='Star rating')),
                ('quote', models.TextField(help_text='Type without quotation marks; they are added for you.', verbose_name='Review')),
                ('name', models.CharField(max_length=60, verbose_name='Customer name')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Square photo works best. If empty, the initials are shown.', max_length=255, null=True, verbose_name='Customer photo')),
                ('role', models.CharField(help_text='e.g. Daily Tech Commuter', max_length=60, verbose_name='Who they are')),
                ('detail', models.CharField(blank=True, help_text='e.g. 340+ rides', max_length=40, verbose_name='Extra detail')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Show green verified tick')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': '10. Testimonials – Reviews',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('badge_text', models.CharField(help_text='e.g. VERIFIED RIDERS', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading')),
                ('description', models.TextField(verbose_name='Paragraph on the right')),
            ],
            options={
                'verbose_name': '10. Testimonials – Heading',
                'verbose_name_plural': '10. Testimonials – Heading',
            },
        ),
    ]
