# Generated by Django 5.2.17 on 2026-09-30 08:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonial_testimonialssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section on website')),
                ('badge_text', models.CharField(help_text='e.g. AVAILABLE ON IOS & ANDROID', max_length=60, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=80, verbose_name='Heading – first line')),
                ('title_highlight', models.CharField(max_length=80, verbose_name='Heading – coloured line')),
                ('text_before_code', models.CharField(max_length=150, verbose_name='Text before promo code')),
                ('promo_code', models.CharField(blank=True, help_text='Shown in a small box. Leave empty for no code.', max_length=30, verbose_name='Promo code')),
                ('text_after_code', models.CharField(blank=True, max_length=150, verbose_name='Text after promo code')),
                ('show_app_store', models.BooleanField(default=True, verbose_name='Show Apple App Store button')),
                ('app_store_small_text', models.CharField(default='DOWNLOAD ON THE', max_length=30, verbose_name='App Store – small text')),
                ('app_store_text', models.CharField(default='Apple App Store', max_length=30, verbose_name='App Store – big text')),
                ('app_store_link', models.URLField(blank=True, help_text='Your app page on the Apple App Store', verbose_name='App Store link')),
                ('show_google_play', models.BooleanField(default=True, verbose_name='Show Google Play button')),
                ('google_play_small_text', models.CharField(default='GET IT ON', max_length=30, verbose_name='Google Play – small text')),
                ('google_play_text', models.CharField(default='Google Play', max_length=30, verbose_name='Google Play – big text')),
                ('google_play_link', models.URLField(blank=True, help_text='Your app page on Google Play', verbose_name='Google Play link')),
                ('show_qr', models.BooleanField(default=True, verbose_name='Show QR code box')),
                ('qr_image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload your QR code (square PNG).', max_length=255, null=True, verbose_name='QR code image')),
                ('qr_title', models.CharField(default='Scan to Download', max_length=40, verbose_name='QR box – heading')),
                ('qr_subtitle', models.CharField(default='Instant Camera Link', max_length=40, verbose_name='QR box – small text')),
            ],
            options={
                'verbose_name': '11. App Download Banner',
                'verbose_name_plural': '11. App Download Banner',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(help_text='e.g. COMPANY', max_length=40, verbose_name='Column heading')),
            ],
            options={
                'verbose_name': 'Footer link column',
                'verbose_name_plural': '12. Footer – Link Columns',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('about_text', models.TextField(verbose_name='Text under the logo')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('address', models.TextField(help_text='Write it the way it should appear, line by line', verbose_name='Address')),
                ('map_link', models.URLField(blank=True, help_text='Optional. Makes the address clickable.', verbose_name='Google Maps link')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('helpdesk_label', models.CharField(default='Help Desk', max_length=30, verbose_name='Mobile – title')),
                ('helpdesk_phone', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('landline_label', models.CharField(default='Land Line', max_length=30, verbose_name='Landline – title')),
                ('landline_phone', models.CharField(blank=True, max_length=20, verbose_name='Landline number')),
                ('copyright_text', models.CharField(help_text='Tip: type {year} to always show the current year, e.g. © {year} NTTS Mobility Technologies.', max_length=150, verbose_name='Copyright line')),
            ],
            options={
                'verbose_name': '12. Footer – Main',
                'verbose_name_plural': '12. Footer – Main',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('label', models.CharField(max_length=50, verbose_name='Link text')),
                ('link', models.CharField(default='#', help_text='A section like #safety, a page, or a full web address', max_length=255, verbose_name='Goes to')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open in new tab')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links in this column',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('platform', models.CharField(choices=[('website', 'Website (globe)'), ('share', 'Share'), ('heart', 'Heart'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp')], max_length=12, verbose_name='Icon')),
                ('link', models.CharField(help_text='Full web address, e.g. https://instagram.com/…', max_length=255, verbose_name='Link')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Social icon',
                'verbose_name_plural': 'Social icons (under the text)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
