# Generated by Django 5.2.17 on 2026-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appdownloadsection_footercolumn_footersettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodal',
            name='email_label',
            field=models.CharField(default='Email Address', max_length=30, verbose_name='Email – title'),
        ),
    ]
