# Generated by Django 5.2.17 on 2026-09-30 08:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bookingmodal_email_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetslide',
            name='ride_card',
            field=models.ForeignKey(blank=True, help_text="The slide shows the car photo already uploaded on this card, so you don't upload it twice.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_slides', to='core.rideoption', verbose_name='Use photo from Fleet & Rides card'),
        ),
        migrations.AlterField(
            model_name='fleetslide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Only if this slide needs its own photo. Car on a transparent background (PNG) works best.', max_length=255, null=True, verbose_name='Different photo (optional)'),
        ),
    ]
