# Generated by Django 5.2.17 on 2026-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fleetslide_ride_card_alter_fleetslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statitem',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('dark', 'Dark'), ('navy', 'Navy blue')], default='green', max_length=10, verbose_name='Number colour'),
        ),
    ]
