# Generated by Django 5.2.17 on 2026-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_statitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='show_call_button',
            field=models.BooleanField(default=True, help_text='Uses the Mobile number above', verbose_name='Show call button'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_email_button',
            field=models.BooleanField(default=True, help_text='Uses the Email above', verbose_name='Show email button'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_floating_buttons',
            field=models.BooleanField(default=True, verbose_name='Show floating contact buttons'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='whatsapp_message',
            field=models.CharField(blank=True, help_text='Typed for the customer when WhatsApp opens (they can change it)', max_length=200, verbose_name='WhatsApp starting message'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='10-digit mobile number. Leave empty to hide the WhatsApp button.', max_length=20, verbose_name='WhatsApp number'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='color',
            field=models.CharField(choices=[('dark', 'Dark'), ('green', 'Green'), ('navy', 'Navy blue')], default='dark', help_text='Colour of the plan name and icon', max_length=10, verbose_name='Accent colour'),
        ),
    ]
