# Generated by Django 5.2.17 on 2026-09-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_footersettings_show_call_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='credit_link',
            field=models.URLField(blank=True, default='https://vetriitsystems.com/', help_text='Opens in a new tab when the credit text is clicked', verbose_name='Credit link'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='credit_text',
            field=models.CharField(blank=True, default='Designed & Developed by Vetri IT Systems', help_text='Leave empty to hide it', max_length=100, verbose_name='Credit text'),
        ),
    ]
