# Generated by Django 5.2.17 on 2026-10-02 08:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_footersettings_credit_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section on website')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. ABOUT US', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=100, verbose_name='Heading')),
                ('description', models.TextField(help_text='Write each paragraph on its own line', verbose_name='Paragraphs')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional. Office, team or fleet photo (landscape works best).', max_length=255, null=True, verbose_name='Photo')),
                ('image_alt', models.CharField(blank=True, help_text='For Google', max_length=150, verbose_name='Photo description')),
                ('mission_title', models.CharField(blank=True, help_text='e.g. Our Mission. Leave empty to hide.', max_length=60, verbose_name='Card 1 – heading')),
                ('mission_text', models.CharField(blank=True, max_length=250, verbose_name='Card 1 – text')),
                ('vision_title', models.CharField(blank=True, help_text='e.g. Our Vision. Leave empty to hide.', max_length=60, verbose_name='Card 2 – heading')),
                ('vision_text', models.CharField(blank=True, max_length=250, verbose_name='Card 2 – text')),
            ],
            options={
                'verbose_name': '13. About Us',
                'verbose_name_plural': '13. About Us',
            },
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='departing_note',
            field=models.CharField(blank=True, help_text='e.g. (Fastest match). Leave empty to hide it.', max_length=60, verbose_name='Departure – note'),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g. ISO 27001 CERTIFIED SAFETY. Leave empty to hide it.', max_length=60, verbose_name='Small tag above heading'),
        ),
    ]
