# Generated by Django 5.2.17 on 2026-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_about_us_after_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(help_text='Write each paragraph on its own line', verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': '11. FAQ – Questions',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this section on website')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. FAQ', max_length=40, verbose_name='Small tag above heading')),
                ('title', models.CharField(max_length=100, verbose_name='Heading')),
                ('description', models.TextField(blank=True, verbose_name='Short paragraph')),
                ('show_help_box', models.BooleanField(default=True, verbose_name='Show “still have questions” box')),
                ('help_title', models.CharField(blank=True, max_length=60, verbose_name='Help box – heading')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='Help box – text')),
                ('help_button_text', models.CharField(blank=True, help_text='Calls the Help Desk number from “12. Footer – Main”. Leave empty to hide.', max_length=40, verbose_name='Help box – call button text')),
            ],
            options={
                'verbose_name': '11. FAQ – Heading',
                'verbose_name_plural': '11. FAQ – Heading',
            },
        ),
        migrations.DeleteModel(
            name='AppDownloadSection',
        ),
    ]
