# Generated by Django 5.2.17 on 2026-10-02 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_faq_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(help_text='e.g. Privacy Policy', max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(help_text="To open this popup from a footer link, set that link's “Goes to” to # + this name, e.g. #privacy-policy", max_length=60, unique=True, verbose_name='Link name')),
                ('intro', models.TextField(blank=True, verbose_name='Opening line')),
                ('content', models.TextField(help_text='Write one point per line. Start a line with # to make it a heading, e.g. # Cancellations', verbose_name='Content')),
                ('updated_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Last updated')),
            ],
            options={
                'verbose_name': 'Policy popup',
                'verbose_name_plural': '14. Policy Popups (Privacy, Terms)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
