# Generated by Django 5.2.17 on 2026-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_legal_content_and_support_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Daily Tech Commuter. Leave empty to hide.', max_length=60, verbose_name='Who they are'),
        ),
    ]
