# Generated by Django 5.2.17 on 2026-10-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_real_customer_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='services',
            field=models.TextField(blank=True, help_text='Write one service per line', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='services_heading',
            field=models.CharField(blank=True, help_text='e.g. Our Fleet Services. Leave empty to hide the list.', max_length=60, verbose_name='Services – heading'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='values_heading',
            field=models.CharField(blank=True, help_text='e.g. Our Value Add. The value cards are added at the bottom of this page.', max_length=60, verbose_name='Values row – heading'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card 3 – text'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_title',
            field=models.CharField(blank=True, help_text='e.g. Why NTTS. Leave empty to hide.', max_length=60, verbose_name='Card 3 – heading'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='mission_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card 1 – text'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='mission_title',
            field=models.CharField(blank=True, help_text='e.g. Mission. Leave empty to hide.', max_length=60, verbose_name='Card 1 – heading'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card 2 – text'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_title',
            field=models.CharField(blank=True, help_text='e.g. Vision. Leave empty to hide.', max_length=60, verbose_name='Card 2 – heading'),
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('icon', models.CharField(choices=[('award', 'Award / badge'), ('clock', 'Clock'), ('target', 'Target'), ('shield', 'Shield'), ('star', 'Star'), ('handshake', 'Handshake')], default='award', max_length=12, verbose_name='Icon')),
                ('title', models.CharField(max_length=60, verbose_name='Heading')),
                ('text', models.CharField(max_length=250, verbose_name='Text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Value card',
                'verbose_name_plural': 'Value cards (e.g. Professionalism, Punctuality, Precision)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
