# Generated by Django 5.2.17 on 2026-10-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pricing_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first, 2 next…', verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('name', models.CharField(help_text='e.g. 4 Hrs / 40 Km', max_length=40, verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Local package',
                'verbose_name_plural': '3. Booking Popup – Local Packages',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bookingmodal',
            name='departing_highlight',
        ),
        migrations.RemoveField(
            model_name='bookingmodal',
            name='departing_label',
        ),
        migrations.RemoveField(
            model_name='bookingmodal',
            name='departing_note',
        ),
        migrations.RemoveField(
            model_name='bookingmodal',
            name='ride_now_label',
        ),
        migrations.RemoveField(
            model_name='bookingmodal',
            name='schedule_label',
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='airport_tab_label',
            field=models.CharField(default='Airport Transfer', max_length=40, verbose_name='Tab 1 – Airport'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='days_label',
            field=models.CharField(default='No of Days', help_text='Outstation tab', max_length=30, verbose_name='Days – title'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='flight_label',
            field=models.CharField(default='Flight Number', help_text='Airport tab', max_length=30, verbose_name='Flight number – title'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='flight_placeholder',
            field=models.CharField(default='e.g. 6E 2134', max_length=60, verbose_name='Flight number – example text'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='local_tab_label',
            field=models.CharField(default='Local – Hourly Rentals', max_length=40, verbose_name='Tab 2 – Local'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='no_cars_text',
            field=models.CharField(default='No cars are available for this trip yet. Please call us to book.', max_length=150, verbose_name='Text when no car has a price'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='outstation_tab_label',
            field=models.CharField(default='Outstation', max_length=40, verbose_name='Tab 3 – Outstation'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='package_heading',
            field=models.CharField(default='Select the Package', help_text='Local – Hourly Rentals tab', max_length=60, verbose_name='Package list heading'),
        ),
        migrations.AddField(
            model_name='bookingmodal',
            name='pax_label',
            field=models.CharField(default='No of Pax', help_text='Outstation tab', max_length=30, verbose_name='Passengers – title'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='extra_charges',
            field=models.CharField(blank=True, max_length=80, verbose_name='Extra charges shown'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='flight_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Flight number'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='num_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No of days'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='num_pax',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No of pax'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='package_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Package'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('airport', 'Airport Transfer'), ('local', 'Local – Hourly Rental'), ('outstation', 'Outstation')], max_length=12, verbose_name='Trip'),
        ),
        migrations.AddField(
            model_name='vehicleclass',
            name='seats',
            field=models.PositiveSmallIntegerField(default=4, help_text="On the Outstation tab, cars with fewer seats than “No of Pax” can't be picked", verbose_name='Passenger seats'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='destination_label',
            field=models.CharField(help_text='Shown on the Airport tab', max_length=40, verbose_name='Drop – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='nearby_suffix',
            field=models.CharField(help_text='The number is added for you: "options" shows as "4 options"', max_length=40, verbose_name='Text after car count'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='schedule_date_label',
            field=models.CharField(default='Pickup Date', max_length=30, verbose_name='Date – title'),
        ),
        migrations.AlterField(
            model_name='bookingmodal',
            name='schedule_time_label',
            field=models.CharField(default='Pickup Time', max_length=30, verbose_name='Time – title'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Drop'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='quoted_price',
            field=models.CharField(blank=True, max_length=60, verbose_name='Price shown'),
        ),
        migrations.CreateModel(
            name='TripRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('airport', 'Airport Transfer'), ('local', 'Local – Hourly Rental'), ('outstation', 'Outstation')], max_length=12, verbose_name='Trip')),
                ('price', models.DecimalField(decimal_places=2, help_text='Numbers only, e.g. 1200', max_digits=9, verbose_name='Price')),
                ('price_suffix', models.CharField(blank=True, help_text='e.g. fixed, per day (250 Km). Can be empty.', max_length=30, verbose_name='Text after price')),
                ('extra_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Extra per Km')),
                ('extra_hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Extra per hour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('package', models.ForeignKey(blank=True, help_text='Only for Local – Hourly Rental', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.rentalpackage', verbose_name='Package')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_rates', to='core.vehicleclass', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': '3. Booking Popup – Prices',
                'ordering': ['vehicle__order', 'vehicle_id', 'trip_type', 'package__order', 'id'],
            },
        ),
    ]
