# Generated by Django 5.2.17 on 2026-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_seo_faq_and_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='pricing_button_text',
            field=models.CharField(default='Pricing Details', help_text='Scrolls down to the Pricing section.', max_length=40, verbose_name='Second button text'),
        ),
    ]
