# Generated by Django 5.2.17 on 2026-10-07 04:49

from django.db import migrations, models

from core.seo_content import STAT_LINKS


def apply_links(apps, schema_editor):
    StatItem = apps.get_model("core", "StatItem")
    for number, url in STAT_LINKS.items():
        StatItem.objects.filter(number=number).update(link=url)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_hero_pricing_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='statitem',
            name='link',
            field=models.URLField(blank=True, help_text='Optional. Clicking the box opens this page in a new tab, e.g. Google reviews.', verbose_name='Link'),
        ),
        migrations.RunPython(apply_links, migrations.RunPython.noop),
    ]
