# Generated by Django 5.2.17 on 2026-10-07 05:10

from django.db import migrations, models

from core.booking_content import CHENNAI_LOCATIONS


def fill_locations(apps, schema_editor):
    apps.get_model("core", "BookingModal").objects.filter(location_suggestions="").update(
        location_suggestions="\n".join(CHENNAI_LOCATIONS))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_package_base_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodal',
            name='location_suggestions',
            field=models.TextField(blank=True, help_text='Place names shown as the customer types, one per line, e.g. T. Nagar. Leave empty to turn off.', verbose_name='Pickup / Drop suggestions'),
        ),
        migrations.RunPython(fill_locations, migrations.RunPython.noop),
    ]
